---

- name: ACI Contract Build
  hosts: apic
  gather_facts: False
  connection: local

  tasks: 
    - name: "Task 1: Gather Login info"
      include_vars: auth/secrets.yml
    
    - name: "Task 2: Set user/pass info"
      set_fact:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"

    - name: "Task 3: Add Var File"
      include_vars: host_vars/vars.yml

    - name: "Task 4: Create a Snapshot"
      aci_config_snapshot:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        export_policy: ansible_snapshot
        max_count: 10
        description: Automation snapshot before configs


    - name: "Task 5: Add a new L3Out"
      aci_l3out:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: "{{ item.tenant }}"
        name: "{{ item.name }}"
        description: "{{ item.descr }}"
        domain: "{{ item.domain }}"
        vrf: "{{ item.vrf }}"
        l3protocol: "{{ item.l3protocol }}"
        route_control: "{{ item.route_control }}"
        state: "{{ item.state }}"
      register: l3_output

      when: (item.state == "present" or item.state == "absent" or item.state == "ignore")

      with_items:
        - "{{ new_l3 }}"
    
    - debug: var=l3_output