---

- name: ACI Contract Build
  hosts: apic
  gather_facts: False
  connection: local

  tasks: 
    - name: "Task 1: Gather Login info"
      include_vars: auth/secrets.yml
    
    - name: "Task 2: Set user/pass info"
      set_fact:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"

    - name: "Task 3: Add Var File"
      include_vars: host_vars/vars.yml

    - name: "Task 4: Add a new VMM domain"
      aci_domain:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        domain: "{{ item.domain }}"
        domain_type: "{{ item.domain_type }}"
        vm_provider: "{{ item.vm_provider }}"
        state: "{{ item.state }}"
      register: new_dom_out

      when: (item.state == "present" or item.state == "absent" or item.state == "ignore")

      with_items:
        - "{{ new_domains }}"

    - debug: var=new_dom_out

