---

- name: Create a Tenant
  hosts: apic
  gather_facts: True
  ignore_errors: Yes
  connection: local

#  vars:
#    ansible_python_interpreter: /usr/lib/python3.7/site-packages/ansible/modules

  tasks: 
    - name: "Task 1: Gather Login info"
      include_vars: auth/secrets.yml
    
    - name: "Task 2: Add Var File"
      include_vars: host_vars/vars.yml

    - name: "Task 3: Query Tenant"
      aci_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}" 
        tenant: "{{ item.name }}"
#        description: "{{ item.description }}"
        state: "{{ item.state }}"
        validate_certs: False

      register: tenant_output

      when: (item.state == "present" or item.state == "absent" or item.state == "query")

      with_items:
        - "{{ tns }}"

    - local_action: copy content="{{tenant_output | to_nice_json}}" dest='output/queries/queries.txt'

    - name: "Task 4: Read Tenant Query"
      shell: cat output/queries/queries.txt
      register: cat_tn_output

    - name: "Task 5: TN Output Query"
      when: cat_tn_output.stdout.find('tn-{{ item.name }}') != -1
      with_items:
        - "{{ tns }}"
      register: cat_tn_query
      debug: msg="The Tenant '{{ item.name }}' already exists"    
    - local_action: copy content="{{ cat_tn_query | to_nice_json}}" dest='output/queries/tn.yml'





