---

- name: Create a Tenant
  hosts: apic
  gather_facts: False
  connection: local

#  vars:
#    ansible_python_interpreter: /usr/lib/python3.7/site-packages/ansible/modules

  tasks: 
    - name: "Task 1: Gather Login info"
      include_vars: auth/secrets.yml
    
    - name: "Task 2: Set user/pass info"
      set_fact:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
    
    - name: "Task 3: Add Var File"
      include_vars: host_vars/vars.yml

    - name: "Task 4: Add New Tenant"
      aci_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}" 
        tenant: "{{ item.name }}"
#        description: "{{ item.description }}"
        state: "{{ item.state }}"
        validate_certs: False

      register: tenant_output

      when: (item.state == "present" or item.state == "absent" or item.state == "query")

      with_items:
        - "{{ tns }}"
      
    - debug: var=tenant_output

    - local_action: copy content="{{tenant_output | to_nice_json}}" dest='output/queries/queries.txt'

    - name: "Task 5: Query for String"
      lineinfile:
        path: output/queries/queries.txt
        line: '"dn": "uni/tn-Shore-Test-1"'
#        marker: " {mark} Ansible TN Query"
        state: present
    
      register: query_results
    
    - debug: var=query_results
  
    - name: "Task 6: Query for String"
      lineinfile:
        path: output/queries/queries.txt
        line: '"dn": "uni/tn-Shore-Test-2"'
#        dest: searches_tst.txt
        state: present
      
      register: query_tn_results

    - debug: var=query_tn_results
  
    - name: "Task 7: Add queries to file"
      blockinfile:
        path: output/queries/queries.txt
        block: |
          "dn": "uni/tn-Shore-Test-1"
          "dn": "uni/tn-Shore-Test-2"
        dest: finders/searches/searches.txt
        marker: " {mark} Ansible Query Section"


        
#    - name: "Task 5: Copy Query Content"
#      copy: 
#        content: "{{ tenant_output.stdout[0] }}\n"
#        dest: "output/queries/queries.txt"





