---

- name: Create a Tenant
  hosts: apic
  gather_facts: False
  connection: local

#  vars:
#    ansible_python_interpreter: /usr/lib/python3.7/site-packages/ansible/modules

  tasks: 
    - name: "Task 1: Gather Login info"
      include_vars: auth/secrets.yml
    
    - name: "Task 2: Set user/pass info"
      set_fact:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
    
    - name: "Task 3: Add Var File"
      include_vars: host_vars/vars.yml

    - name: "Task 4: Add New Tenant"
      aci_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}" 
        tenant: "{{ item.name }}"
#        description: "{{ item.description }}"
        state: "{{ item.state }}"
        validate_certs: False

      register: tenant_output

      when: (item.state == "present" or item.state == "absent" or item.state == "query")

      with_items:
        - "{{ tns }}"
      
    - debug: var=tenant_output



