---
aci_apic:
  host: "apic"
  ipv4: 64.103.37.54

#Build Infra Section
tns:  
  - name: Auto_Test_1
    descr: 1st tenant
    state: ignore
  
  - name: Auto_Test_2
    descr: 2nd tenant
    state: ignore

vrfs:
  - name: AT1
    tenant: Auto_Test_1
    descr: Auto_VRF_1
    policy_control_preference: enforced
    policy_control_direction: ingress
    state: ignore

  - name: AT2
    descr: Auto_VRF_2
    tenant: Auto_Test_2
    policy_control_preference: enforced
    policy_control_direction: ingress
    state: ignore

cons: 
  - name: permit_all
    descr: Auto_Test_1_contract
    tenant: Auto_Test_1
    scope: application-profile
    state: ignore

  - name: permit_all
    descr: Auto_Test_2_contract
    tenant: Auto_Test_2
    scope: application-profile
    state: ignore 

  - name: db_contract
    descr: Auto_Test_1_contract
    tenant: Auto_Test_1
    scope: application-profile
    state: ignore
  
  - name: web_contract
    descr: Auto_Test_1_contract
    tenant: Auto_Test_1
    scope: application-profile
    state: ignore

  - name: db_contract
    descr: Auto_Test_2_contract
    tenant: Auto_Test_2
    scope: application-profile
    state: ignore 

  - name: web_contract
    descr: Auto_Test_2_contract
    tenant: Auto_Test_2
    scope: application-profile
    state: ignore 

#Build Apps Section

apps:
  - name: web_app_01
    descr: web_app
    tenant: Auto_Test_1
    state: ignore

  - name: db_app_01
    descr: dbb_app
    tenant: Auto_Test_1
    state: ignore 

  - name: pres_app_01
    descr: pres_app
    tenant: Auto_Test_1
    state: ignore

  - name: web_app_02
    descr: web_app
    tenant: Auto_Test_2
    state: ignore

  - name: db_app_02
    descr: dbb_app
    tenant: Auto_Test_2
    state: ignore 

  - name: pres_app_02
    descr: pres_app
    tenant: Auto_Test_2
    state: ignore