---
aci_apic:
  host: "apic"
  ipv4: 64.103.37.54

#Build Infra Section
tns:  
  - name: Shore_Test_1
    descr: 1st tenant
    state: present
  
  - name: Shore_Test_2
    descr: 2nd tenant
    state: present

vrfs:
  - name: AT1
    tenant: Shore_Test_1
    descr: Auto_VRF_1
    policy_control_preference: enforced
    policy_control_direction: ingress
    state: present

  - name: AT2
    descr: Auto_VRF_2
    tenant: Shore_Test_2
    policy_control_preference: enforced
    policy_control_direction: ingress
    state: present

cons: 
  - name: permit_all
    descr: Shore_Test_1_contract
    tenant: Shore_Test_1
    scope: application-profile
    state: present

  - name: permit_all
    descr: Shore_Test_2_contract
    tenant: Shore_Test_2
    scope: application-profile
    state: present 

  - name: db_contract
    descr: Shore_Test_1_contract
    tenant: Shore_Test_1
    scope: application-profile
    state: present
  
  - name: web_contract
    descr: Shore_Test_1_contract
    tenant: Shore_Test_1
    scope: application-profile
    state: present

  - name: db_contract
    descr: Shore_Test_2_contract
    tenant: Shore_Test_2
    scope: application-profile
    state: present 

  - name: web_contract
    descr: Shore_Test_2_contract
    tenant: Shore_Test_2
    scope: application-profile
    state: present 

#Build Apps Section

apps:
  - name: app01
    descr: new_app
    tenant: Shore_Test_1
    state: present

  - name: app02
    descr: new_app
    tenant: Shore_Test_2
    state: present

bds:
  - name: app01-web-bd
    descr: app-bd
    tenant: Shore_Test_1
    vrf: AT1
    state: present
  
  - name: app01-pres-bd
    descr: app-bd
    tenant: Shore_Test_1
    vrf: AT1
    state: present
  
  - name: app01-db-bd
    descr: app-bd
    tenant: Shore_Test_1
    vrf: AT1
    state: present

  - name: app02-web-bd
    descr: app-bd
    tenant: Shore_Test_2
    vrf: AT2
    state: present

  - name: app02-pres-bd
    descr: app-bd
    tenant: Shore_Test_2
    vrf: AT2
    state: present

  - name: app02-db-bd
    descr: app-bd
    tenant: Shore_Test_2
    vrf: AT2
    state: present
