---

- name: ACI Contract Build
  hosts: apic
  gather_facts: False
  connection: local

  vars_prompt:
  - name: ref_prompt
    prompt: "CR Number"
    private: no

  tasks: 
    - name: "Task 1: Gather Login info"
      include_vars: auth/secrets.yml

    - name: "Task 2: Gather Reference Number"
      set_fact:
        reference: "{{ ref_prompt }}"
    
    - name: "Task 3: Set user/pass info"
      set_fact:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"

    - name: "Task 4: Update '{{ inventory_hostname }}'' from CSV"
      include: csv_contract_vars.yml

    - name: "Task 5: Add Var File"
      include_vars: host_vars/vars.yml

    - name: "Task 6: Create a Snapshot"
      aci_config_snapshot:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        export_policy: ansible_snapshot
        max_count: 10
        validate_certs: no
        description: Automation snapshote before configs

    - name: "Task 7: Add a new contract to tenant"
      aci_contract:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}" 
        password: "{{ password }}"
        tenant: "{{ item.tenant }}"
        contract: "{{ item.name }}"
        description: Communication between APPs
        scope: "{{ item.scope }}"
        state: "{{ item.state }}"
        validate_certs: False

      register: contract_output

      when: (item.state == "present" or item.state == "absent" or item.state == "ignore")

      with_items:
        - "{{ cons }}"
    
    - debug: var=contract_output

    - name: "Task 8: Add Contract subject to Contract "
      aci_contract_subject:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}" 
        password: "{{ password }}"
        tenant: "{{ item.tenant }}"
        contract: "{{ item.contract }}"
        subject: "{{ item.name }}"
        reverse_filter: "{{ item.reverse_filter }}"
        priority: "{{ item.priority }}"
        state: present
        validate_certs: no 
      register: con-subject_output

      when: (item.state == "present" or item.state == "absent" or item.state == "ignore")

      with_items:
        - "{{ con_sub }}"
    
    - debug: var=con-subject_output
    
    - name: "Task 11: Change 'present' to 'query' "
      replace: 
        path: host_vars/vars.yml
        regexp: 'state: present'
        replace: 'state: query'
        before: '#EOS'

    - name: "Task 12: Change 'absent' to 'query' "
      replace: 
        path: host_vars/vars.yml
        regexp: 'state: present'
        replace: 'state: query'
        before: '#EOS'
    
    - name: "Task 13: Copy var file to new location"
      copy: 
        src: host_vars/vars.yml
        dest: completed_plays/{{reference}}-vars_play.yml
        mode: preserve

    - name: "Task 14: Clear Contract contents of host_vars template"
      blockinfile:
        path: host_vars/vars.yml
        marker: "# {mark} Ansible CON Section"
        state: absent

    - name: "Task 15: Clear Contract Subject contents of host_vars template"
      blockinfile:
        path: host_vars/vars.yml
        marker: "# {mark} Ansible CON_Sub Section"
        state: absent