---

- name: ACI Contract Build
  hosts: apic
  gather_facts: False
  connection: local

  tasks: 
    - name: "Task 1: Gather Login info"
      include_vars: auth/secrets.yml
    
    - name: "Task 2: Set user/pass info"
      set_fact:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"

    - name: "Task 3: Add Var File"
      include_vars: host_vars/vars.yml

    - name: "Task 4: Add a new contract to tenant"
      aci_contract:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}" 
        password: "{{ password }}"
        tenant: "{{ item.tenant }}"
        contract: "{{ item.name }}"
        description: Communication between APPs
        scope: "{{ item.scope }}"
        state: "{{ item.state }}"
        validate_certs: False

      register: contract_output

      when: (item.state == "present" or item.state == "absent" or item.state == "ignore")

      with_items:
        - "{{ cons }}"
    
    - debug: var=contract_output
