---

- name: ACI Fabric Build
  hosts: apic
  gather_facts: False
  ignore_errors: Yes
  connection: local

  vars_prompt:
  - name: ref_prompt
    prompt: "CR Number"
    private: no  

  tasks: 
    - name: "Task 1: Gather Login info"
      include_vars: auth/secrets.yml
  
    - name: "Task 2: Gather Reference Number"
      set_fact:
        reference: "{{ ref_prompt }}"
    
    - name: "Task 3: Set user/pass info"
      set_fact:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"

    - name: "Task 4: Update '{{ inventory_hostname }}'' from CSV"
      include: csv_fabric_vars.yml

    - name: "Task 5: Add Var File"
      include_vars: host_vars/vars.yml

    - name: "Task 6: Create a Snapshot"
      aci_config_snapshot:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        export_policy: ansible_snapshot
        max_count: 10
        description: Automation snapshot before configs

    - name: "Task 7: Create Port-Channel Policy"
      aci_interface_policy_port_channel:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        port_channel: '{{ item.name }}'
        mode: '{{ item.mode }}'
        state: "{{ item.state }}"
      register: pc_result

      when: (item.state == "present" or item.state == "absent" or item.state == "query")

      with_items:
        - "{{ port_channel }}"

    - debug: var=pc_result

    - name: "Task 8: Change 'present' to 'query' "
      replace: 
        path: host_vars/vars.yml
        regexp: 'state: present'
        replace: 'state: query'
        before: '#EOF'

    - name: "Task 9: Change 'absent' to 'query' "
      replace: 
        path: host_vars/vars.yml
        regexp: 'state: present'
        replace: 'state: query'
        before: '#EOF'

    - name: "Task 10: Copy var file to new location"
      copy: 
        src: host_vars/vars.yml
        dest: completed_plays/{{reference}}-vars_play.yml
        mode: preserve
    
    - name: "Task 11: Clear LLDP contents of host_vars template"
      blockinfile:
        path: host_vars/vars.yml
        marker: "# {mark} Ansible LLDP Section"
        state: absent