---
aci_apic:
  host: "apic"
  ipv4: 64.103.37.54

#Build Infra Section
tns:  
  - name: Shore-Test-1
    descr: 1st tenant
    state: query
  
  - name: Shore_Test_2
    descr: 2nd tenant
    state: query

vrfs:
  - name: AT1
    tenant: Shore-Test-1
    descr: Auto_VRF_1
    policy_control_preference: enforced
    policy_control_direction: ingress
    state: query

  - name: AT2
    descr: Auto_VRF_2
    tenant: Shore_Test_2
    policy_control_preference: enforced
    policy_control_direction: ingress
    state: query

cons: 
  - name: permit_all
    descr: Shore-Test-1_contract
    tenant: Shore-Test-1
    scope: application-profile
    state: query

  - name: permit_all
    descr: Shore_Test_2_contract
    tenant: Shore_Test_2
    scope: application-profile
    state: query 

  - name: db_contract
    descr: Shore-Test-1_contract
    tenant: Shore-Test-1
    scope: application-profile
    state: query
  
  - name: web_contract
    descr: Shore-Test-1_contract
    tenant: Shore-Test-1
    scope: application-profile
    state: query

  - name: db_contract
    descr: Shore_Test_2_contract
    tenant: Shore_Test_2
    scope: application-profile
    state: query 

  - name: web_contract
    descr: Shore_Test_2_contract
    tenant: Shore_Test_2
    scope: application-profile
    state: query 
#EOS
# Build Apps Section

apps:
  - name: app01
    descr: new_app
    tenant: Shore-Test-1
    state: query

  - name: app02
    descr: new_app
    tenant: Shore_Test_2
    state: query

bds:
  - name: app01-web-bd
    descr: app-bd
    tenant: Shore-Test-1
    vrf: AT1
    state: query
  
  - name: app01-pres-bd
    descr: app-bd
    tenant: Shore-Test-1
    vrf: AT1
    state: query
  
  - name: app01-db-bd
    descr: app-bd
    tenant: Shore-Test-1
    vrf: AT1
    state: query

  - name: app02-web-bd
    descr: app-bd
    tenant: Shore_Test_2
    vrf: AT2
    state: query

  - name: app02-pres-bd
    descr: app-bd
    tenant: Shore_Test_2
    vrf: AT2
    state: query

  - name: app02-db-bd
    descr: app-bd
    tenant: Shore_Test_2
    vrf: AT2
    state: query

epgs:
  - name: app01-web-epg
    descr: app01-web-epg
    tenant: Shore-Test-1
    ap: app01
    bd: app01-web-bd
    preferred_group: yes
    state: query

  - name: app01-pres-epg
    descr: app01-pres-epg
    tenant: Shore-Test-1
    ap: app01
    bd: app01-pres-bd
    preferred_group: yes
    state: query

  - name: app01-db-epg
    descr: app01-db-epg
    tenant: Shore-Test-1
    ap: app01
    bd: app01-db-bd
    preferred_group: yes
    state: query

  - name: app02-web-epg
    descr: app02-web-epg
    tenant: Shore_Test_2
    ap: app02
    bd: app02-web-bd
    preferred_group: yes
    state: query

  - name: app02-pres-epg
    descr: app02-pres-epg
    tenant: Shore_Test_2
    ap: app02
    bd: app02-pres-bd
    preferred_group: yes
    state: query

  - name: app02-db-epg
    descr: app02-db-epg
    tenant: Shore_Test_2
    ap: app02
    bd: app02-db-bd
    preferred_group: yes
    state: query

  - name: app02-db2-epg
    descr: app02-db2-epg
    tenant: Shore_Test_2
    ap: app02
    bd: app02-db-bd
    preferred_group: yes
    state: absent

subs:
  - name: app01-web-bd/24
    tenant: Shore-Test-1
    bd: app01-web-bd
    gateway: 192.168.1.1
    mask: 24
    scope: public
    state: query

  - name: app01-pres-bd/24
    tenant: Shore-Test-1
    bd: app01-pres-bd
    gateway: 192.168.2.1
    mask: 24
    scope: public
    state: query

  - name: app01-db-bd/24
    tenant: Shore-Test-1
    bd: app01-db-bd
    gateway: 192.168.3.1
    mask: 24
    scope: public
    state: query

  - name: app02-web-bd/24
    tenant: Shore_Test_2
    bd: app02-web-bd
    gateway: 172.16.1.1
    mask: 24
    scope: public
    state: query

  - name: app02-pres-bd/24
    tenant: Shore_Test_2
    bd: app02-pres-bd
    gateway: 172.16.2.1
    mask: 24
    scope: public
    state: query 

  - name: app02-db-bd/24
    tenant: Shore_Test_2
    bd: app02-db-bd
    gateway: 172.16.3.1
    mask: 24
    scope: public
    state: query 

con_bindings:
  - name: con_binding
    tenant: Shore-Test-1
    ap: app01
    epg: app01-web-epg
    contract: web_contract
    contract_type: provider
    state: query

  - name: con_binding2
    tenant: Shore-Test-1
    ap: app01
    epg: app01-pres-epg
    contract: permit_all
    contract_type: provider
    state: query

  - name: con_binding3
    tenant: Shore-Test-1
    ap: app01
    epg: app01-db-epg
    contract: db_contract
    contract_type: provider
    state: query

  - name: con_binding4
    tenant: Shore_Test_2
    ap: app02
    epg: app02-web-epg
    contract: web_contract
    contract_type: provider
    state: query

  - name: con_binding5
    tenant: Shore_Test_2
    ap: app02
    epg: app02-pres-epg
    contract: permit_all
    contract_type: provider
    state: query

  - name: con_binding6
    tenant: Shore_Test_2
    ap: app02
    epg: app02-db-epg
    contract: db_contract
    contract_type: provider
    state: query

domains:
  - name: domain1
    tenant: Shore-Test-1
    ap: app01
    epg: app01-web-epg
    domain: spod1
    domain_type: vmm
    vm_provider: vmware
    deploy_immediacy: immediate
    resolution_immediacy: immediate
    state: query

  - name: domain2
    tenant: Shore-Test-1
    ap: app01
    epg: app01-pres-epg
    domain: spod1
    domain_type: vmm
    vm_provider: vmware
    deploy_immediacy: immediate
    resolution_immediacy: immediate
    state: query

  - name: domain3
    tenant: Shore-Test-1
    ap: app01
    epg: app01-db-epg
    domain: spod1
    domain_type: vmm
    vm_provider: vmware
    deploy_immediacy: immediate
    resolution_immediacy: immediate
    state: query

  - name: domain4
    tenant: Shore_Test_2
    ap: app02
    epg: app02-web-epg
    domain: spod1
    domain_type: vmm
    vm_provider: vmware
    deploy_immediacy: immediate
    resolution_immediacy: immediate
    state: query

  - name: domain5
    tenant: Shore_Test_2
    ap: app02
    epg: app02-pres-epg
    domain: spod1
    domain_type: vmm
    vm_provider: vmware
    deploy_immediacy: immediate
    resolution_immediacy: immediate
    state: query

  - name: domain6
    tenant: Shore_Test_2
    ap: app02
    epg: app02-db-epg
    domain: spod1
    domain_type: vmm
    vm_provider: vmware
    deploy_immediacy: immediate
    resolution_immediacy: immediate
    state: query

new_domains:
  - name: hyperv_test
    domain: spod1
    domain_type: vmm
    vm_provider: vmware
    state: query

new_l3:
  - name: ospf_test
    tenant: Shore-Test-1
    descr: test_l3out
    domain: spod1
    vrf: AT1
    l3protocol: ospf
    route_control: export
    state: present

  - name: ospf_test
    tenant: Shore_Test_2
    descr: test_l3out
    domain: spod1
    vrf: AT1
    l3protocol: ospf
    route_control: export
    state: query

l3outs:
  - name: app01-web-bd-l3
    tenant: Shore-Test-1
    bd: app01-web-bd
    l3out: ospf_test
    state: query

  - name: app01-pres-bd-l3
    tenant: Shore-Test-1
    bd: app01-pres-bd
    l3out: ospf_test
    state: query

  - name: app01-db-bd-l3
    tenant: Shore-Test-1
    bd: app01-db-bd
    l3out: ospf_test
    state: query

  - name: app02-web-bd-l3
    tenant: Shore_Test_2
    bd: app02-web-bd
    l3out: ospf_test
    state: query

  - name: app02-pres-bd-l3
    tenant: Shore_Test_2
    bd: app02-pres-bd
    l3out: ospf_test
    state: query

  - name: app02-db-bd-l3
    tenant: Shore_Test_2
    bd: app02-db-bd
    l3out: ospf_test
    state: query
#EOF



  






    
