---

- name: ACI Apps Build
  hosts: apic
  gather_facts: False
  connection: local

  tasks: 
    - name: "Task 1: Gather Login info"
      include_vars: auth/secrets.yml
    
    - name: "Task 2: Set user/pass info"
      set_fact:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"

    - name: "Task 3: Add Var File"
      include_vars: host_vars/vars.yml

    - name: Add a new AP
      aci_ap:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: "{{ item.tenant }}"
        ap: "{{ item.name }}"
        description: "{{ item.descr }}"
        state: "{{ item.state }}"
      register: app_output
      when: (item.state == "present" or item.state == "absent" or item.state == "ignore")

      with_items:
        - "{{ apps }}"

    - debug: var=app_output

    - name: Add Bridge Domain
      aci_bd:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{ item.tenant }}"
        bd: "{{ item.name }}"
        vrf: "{{ item.vrf }}"
        state: "{{ item.state }}"
      register: bd_out

      when: (item.state == "present" or item.state == "absent" or item.state == "ignore")

      with_items: 
        - "{{ bds }}"



#    - name: "Task: 4 Add a new EPG"
#      aci_epg:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        tenant: "{{ item.tenant }}"
#        ap: intranet
#        epg: web_epg
#        description: Web Intranet EPG
#        bd: prod_bd
#        preferred_group: yes
#        state: present

