---
aci_apic:
  host: "apic"
  ipv4: 64.103.37.54

#Build Infra Section
tns:  
  - name: Shore_Test_1
    descr: 1st tenant
    state: present
  
  - name: Shore_Test_2
    descr: 2nd tenant
    state: present

vrfs:
  - name: AT1
    tenant: Shore_Test_1
    descr: Auto_VRF_1
    policy_control_preference: enforced
    policy_control_direction: ingress
    state: present

  - name: AT2
    descr: Auto_VRF_2
    tenant: Shore_Test_2
    policy_control_preference: enforced
    policy_control_direction: ingress
    state: present

cons: 
  - name: permit_all
    descr: Shore_Test_1_contract
    tenant: Shore_Test_1
    scope: application-profile
    state: present

  - name: permit_all
    descr: Shore_Test_2_contract
    tenant: Shore_Test_2
    scope: application-profile
    state: present 

  - name: db_contract
    descr: Shore_Test_1_contract
    tenant: Shore_Test_1
    scope: application-profile
    state: present
  
  - name: web_contract
    descr: Shore_Test_1_contract
    tenant: Shore_Test_1
    scope: application-profile
    state: present

  - name: db_contract
    descr: Shore_Test_2_contract
    tenant: Shore_Test_2
    scope: application-profile
    state: present 

  - name: web_contract
    descr: Shore_Test_2_contract
    tenant: Shore_Test_2
    scope: application-profile
    state: present 

#Build Apps Section

apps:
  - name: app01
    descr: new_app
    tenant: Shore_Test_1
    state: present

  - name: app02
    descr: new_app
    tenant: Shore_Test_2
    state: present

bds:
  - name: app01-web-bd
    descr: app-bd
    tenant: Shore_Test_1
    vrf: AT1
    state: present
  
  - name: app01-pres-bd
    descr: app-bd
    tenant: Shore_Test_1
    vrf: AT1
    state: present
  
  - name: app01-db-bd
    descr: app-bd
    tenant: Shore_Test_1
    vrf: AT1
    state: present

  - name: app02-web-bd
    descr: app-bd
    tenant: Shore_Test_2
    vrf: AT2
    state: present

  - name: app02-pres-bd
    descr: app-bd
    tenant: Shore_Test_2
    vrf: AT2
    state: present

  - name: app02-db-bd
    descr: app-bd
    tenant: Shore_Test_2
    vrf: AT2
    state: present

epgs:
  - name: app01-web-epg
    descr: app01-web-epg
    tenant: Shore_Test_1
    ap: app01
    bd: app01-web-bd
    preferred_group: yes
    state: present

  - name: app01-pres-epg
    descr: app01-pres-epg
    tenant: Shore_Test_1
    ap: app01
    bd: app01-pres-bd
    preferred_group: yes
    state: present

  - name: app01-db-epg
    descr: app01-db-epg
    tenant: Shore_Test_1
    ap: app01
    bd: app01-db-bd
    preferred_group: yes
    state: present

  - name: app02-web-epg
    descr: app02-web-epg
    tenant: Shore_Test_2
    ap: app02
    bd: app02-web-bd
    preferred_group: yes
    state: present

  - name: app02-pres-epg
    descr: app02-pres-epg
    tenant: Shore_Test_2
    ap: app02
    bd: app02-pres-bd
    preferred_group: yes
    state: present

  - name: app02-db-epg
    descr: app02-db-epg
    tenant: Shore_Test_2
    ap: app02
    bd: app02-db-bd
    preferred_group: yes
    state: present

  - name: app02-db2-epg
    descr: app02-db2-epg
    tenant: Shore_Test_2
    ap: app02
    bd: app02-db-bd
    preferred_group: yes
    state: absent

subs:
  - name: app01-web-bd/24
    tenant: Shore_Test_1
    bd: app01-web-bd
    gateway: 192.168.1.1
    mask: 24
    scope: public
    state: present

  - name: app01-pres-bd/24
    tenant: Shore_Test_1
    bd: app01-pres-bd
    gateway: 192.168.2.1
    mask: 24
    scope: public
    state: present

  - name: app01-db-bd/24
    tenant: Shore_Test_1
    bd: app01-db-bd
    gateway: 192.168.3.1
    mask: 24
    scope: public
    state: present

  - name: app02-web-bd/24
    tenant: Shore_Test_2
    bd: app02-web-bd
    gateway: 172.16.1.1
    mask: 24
    scope: public
    state: present

  - name: app02-pres-bd/24
    tenant: Shore_Test_2
    bd: app02-pres-bd
    gateway: 172.16.2.1
    mask: 24
    scope: public
    state: present 

  - name: app02-db-bd/24
    tenant: Shore_Test_2
    bd: app02-db-bd
    gateway: 172.16.3.1
    mask: 24
    scope: public
    state: present 

con_bindings:
  - name: con_binding
    tenant: Shore_Test_1
    ap: app01
    epg: app01-web-epg
    contract: web_contract
    contract_type: provider
    state: present

  - name: con_binding2
    tenant: Shore_Test_1
    ap: app01
    epg: app01-pres-epg
    contract: permit_all
    contract_type: provider
    state: present

  - name: con_binding3
    tenant: Shore_Test_1
    ap: app01
    epg: app01-db-epg
    contract: db_contract
    contract_type: provider
    state: present

  - name: con_binding4
    tenant: Shore_Test_2
    ap: app02
    epg: app02-web-epg
    contract: web_contract
    contract_type: provider
    state: present

  - name: con_binding5
    tenant: Shore_Test_2
    ap: app02
    epg: app02-pres-epg
    contract: permit_all
    contract_type: provider
    state: present

  - name: con_binding6
    tenant: Shore_Test_2
    ap: app02
    epg: app02-db-epg
    contract: db_contract
    contract_type: provider
    state: present


    
