---
aci_apic:
  host: "apic"
  ipv4: 64.103.37.54

#Build Section
tns:  
  - name: Shore-Test-1
    descr: 1st tenant
    state: query
  
  - name: Shore-Test-2
    descr: 2nd tenant
    state: query

vrfs:
  - name: AT1
    descr: Auto_VRF_1
    policy_control_preference: enforced
    policy_control_direction: ingress
    state: present

  - name: AT2
    descr: Auto_VRF_2
    policy_control_preference: enforced
    policy_control_direction: ingress
    state: present
