---

- name: Create a Tenant
  hosts: apic
  gather_facts: False
  connection: local

#  vars:
#    ansible_python_interpreter: /usr/lib/python3.7/site-packages/ansible/modules

  tasks: 
    - name: "Task 1: Gather Login info"
      include_vars: auth/secrets.yml
    
    - name: "Task 2: Add New Tenant"
      aci_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}" 
        tenant: Auto_Testing_TN
        state: present
        validate_certs: False
#      delegate_to: localhost

      register: tenant_output
      
    - debug: var=tenant_output



